name: gherkin
version: 0.0.5
description: A Gherkin parsers and runner for Dart which is very similar to Cucumber, it provides the base BDD functionality ready for use in platform specific implementations i.e. flutter/web
author: Jon Samwell <jonsamwell@gmail.com>
homepage: https://github.com/jonsamwell/dart_gherkin

dependencies:
  glob: ^1.1.7
  path: ^1.6.2
  test: ^1.5.3
  matcher: ^0.12.3

dev_dependencies:
  pedantic: ^1.7.0

environment:
  sdk: ">=2.1.0 <3.0.0"
