name: gherkin
version: 0.0.2
description: A Gherkin parsers and runner for Dart which is very similar to cucumber it provides the base DBB functionality ready to be used in platform specific use-cases i.e. flutter/web
author: Jon Samwell <jonsamwell@gmail.com>
homepage: https://github.com/jonsamwell/dart_gherkin

dependencies:
  glob: ^1.1.7
  path: ^1.6.2
  test: ^1.5.3
  matcher: ^0.12.3

dev_dependencies:

environment:
  sdk: ">=2.1.0 <3.0.0"
