name: gherkin
version: 0.0.1
description: a dart implementation of Gherkin
author: Jon Samwell <jonsamwell@gmail.com>
homepage: https://github.com/jonsamwell/dart_gherkin

dependencies:
  glob: ^1.1.7
  path: ^1.6.2
  test: ^1.5.3

dev_dependencies:

environment:
  sdk: ">=2.1.0 <3.0.0"